### ISSUE TITLE
seaching and filtering function

### ISSUE THREAD

**Issue by dcarver1** [dcarver1/cwrUSA_maps#1]
The attached xlsx document contains all the additional attribute data that search and filtering would require. 

To start, it would be great to be able to have a relative search that utilizes the common name (column f) and allows for search on the genus. 

ex: when you type pecan, all 15 species in the carya genus appear as selectable features. 

Other columns would be more interesting for developing filters. 
The information present in columns B:F and Z:AA will not be present in the htmls 
The information in columns G:Y is present in the htmls as tables. So indexing via a text search might be challenging?

**Comment by kevinworthington** [comment]
I think we've covered all the bases here.
